#repos:
# - repo: local
#   hooks:
#      - id: pytestCoverage
#        name: pytest with coverage
#        entry: python tools/checkCoverage.py
#        language: system
#        pass_filenames: false
#        always_run: true
#  - repo: https://github.com/psf/black
#    rev: 24.1.0
#    hooks:
#      - id: black
#  - repo: https://github.com/PyCQA/isort
#    rev: 5.12.0
#    hooks:
#      - id: isort
  


