
[settings]
nSteps = 500 # Number of Total steps
tStart = 0.0 # Start time of simulation
tEnd = 0.5 # End time of simulation

[geometry]
meshName = "Example/Geometry/bay.msh" # Path to mesh file
borders = [[0, 0.45], [0, 0.2]] # Borders for Fish [x_min, y_min], [x_max, y_max]
ship = [0.45, 0.4] # Oil collection ship position [x, y]
source = [0.35, 0.45] # Oil source/injection position [x, y] (optional)

[IO]
logName = "log" #TODO this need to do somthing
writeFrequency = 20 # Frequency of writing output data 0 is no output

[video]
createVideo = true # Enable or disable video creation
videoFPS = 30 # Frames per second for the video