[settings]
pathToSimConfig = "Example/SimConfig/" # Path to simulation config files


[UI]
enableUI = true # Enable or disable the user interface
colorScheme = "viridis" # Color scheme for the UI (options: matplotlib schemes)